# Generated by Django 2.1.4 on 2019-01-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lising_id',
            new_name='listing_id',
        ),
    ]
